remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Discord Bot Studio
show_downloads: true
github:
  zip_url: https://github.com/discordbotstudios/discordbotstudio/releases/download/Release/DBSUpdater.exe
  tar_url : https://github.com/discordbotstudios/discordbotstudio/releases/download/Release/DBSUpdater.exe
